### ISSUE TITLE
ACMEv2 support

### ISSUE THREAD

**Issue by themifuru** [diafygi/gethttpsforfree#150]
https://community.letsencrypt.org/t/acmev2-and-wildcard-launch-delay/53654/42

WHEN?

**Comment by kevinbalicot** [comment]
👍

**Comment by diafygi** [comment]
I plan on working on this after the launch of v2 settles down. I wouldn't be surprised if there's a few bug fixes in the first few weeks.

**Comment by themifuru** [comment]
v2 already launched

**Comment by themifuru** [comment]
up

**Comment by diafygi** [comment]
Ok, I pushed a beta version for ACME v2 (including wildcard support). Can y'all please try it out and report bugs? Thanks!

Website: https://gethttpsforfree.com/v2/
Code: https://github.com/diafygi/gethttpsforfree/tree/gh-pages/v2

**Comment by diafygi** [comment]
The javascript is quite a bit longer for a few reasons.

First, the added DNS support adds a whole other option (and thus more code).

Second, each signature now requires a form submission so that I can get the next nonce (since nonce timeouts are becoming more common, e.g. #149  ).

Third, I wanted to get the beta out and was okay with making it super verbose. I could probably spend a while really reducing/simplifying the code, but eh, we'll see if/when that happens. It's pretty well commented, so it shouldn't be mega-spaghetti.

**Comment by themifuru** [comment]
delete 1st step or create analogue

**Comment by diafygi** [comment]
@owner I don't really understand what you mean. Can you please explain more?

**Comment by themifuru** [comment]
Please, delete first step and **save only four**. Because - i dont want create a personal PGP-key for email.

**Comment by diafygi** [comment]
Hmmm, I'm still confused. You don't need a PGP key, but you do need an account key (`openssl genrsa 4096 > account.key; openssl rsa -in account.key -pubout`). That is a requirement in the ACME spec, so that step has to stay.

As for the email, you can make up an email if you want. There's no verification (other than it being a valid domain), and it only exists to notify you when your certificate has expired.

So Step 1 is staying.

**Comment by diafygi** [comment]
I'm closing this issue since v2 is launched.
